### ISSUE TITLE
No attributte added to the images

### ISSUE THREAD

**Issue by sanPuerquitoProgramador** [bennothommo/wn-lazy-load-plugin#1]
Hi, I'm using your plugin, thanks. 

All the images have the width and height attribute but when I inspect the code there is not loading attribute added to the images.

<img width="1122" alt="Captura de pantalla 2022-10-31 a la(s) 21 58 53" src="https://user-images.githubusercontent.com/8864253/199155739-94279ff1-3d22-496e-b680-b98ec94ba291.png">

What am I Missing?

**Comment by bennothommo** [comment]
@sanPuerquitoProgramador thanks for the report.

It's likely the plugin isn't running. I just checked an install and found that if you installed this via Composer, it would create the plugin directory as `plugins/bennothommo/lazy-load` which is not read in Winter. I've released a new version of this plugin which fixes this by installing the plugin as `plugins/bennothommo/lazyload` (without the dash).

You should be able to delete the plugin from your site in the old location and run `composer update` to get the latest version of the plugin with this fixed.
